- inji-verify/src/components/Home/VerificationSection/UploadQrCode.tsx
> [INJIVER-142] Remove pdf support

- inji-verify/package-lock.json
- inji-verify/package.json
> Fix build issue - Update pixel pass version

- inji-verify/package-lock.json
- inji-verify/package.json
> Fix build fail - Update pixel pass library

- .github/workflows/push-trigger.yml
> [INJIVER-140] Added sonar analysis job to the workflows

- inji-verify/src/components/Home/VerificationSection/QrScanner.tsx
This reverts commit 33418ab41efecd3de67acee1501d6012891dbc8c.
> Revert "[INJIVER-139] Added option to select rear camera by default"

- inji-verify/src/components/Home/VerificationSection/ScanQrCode.tsx
- inji-verify/src/components/Home/VerificationSection/UploadQrCode.tsx
- inji-verify/src/components/PageTemplate/index.tsx
- inji-verify/src/components/commons/Loader.tsx
- inji-verify/src/components/commons/LoaderWithBackdrop.tsx
- inji-verify/src/components/misc/CheckingForInternetConnectivity.tsx
- inji-verify/src/redux/features/application-state/application-state.selector.ts
- inji-verify/src/redux/features/application-state/application-state.slice.ts
- inji-verify/src/redux/features/verification/verification.saga.ts
- inji-verify/src/redux/features/verification/verification.selector.ts
- inji-verify/src/redux/features/verification/verification.slice.ts
- inji-verify/src/redux/store.ts
- inji-verify/src/types/data-types.ts
- inji-verify/src/utils/config.ts
- inji-verify/src/utils/misc.ts
These changes are fix to the issue where the offline page appears sometimes in the middle of the verification.
> Cherrypick INJIVER 233 changes to release0.9.x

- .github/workflows/push-trigger.yml
- inji-verify/src/components/Home/Header/VerificationMethodTabs/index.tsx
- inji-verify/src/components/Home/VerificationSection/QrScanner.tsx
- inji-verify/src/components/Home/VerificationSection/Result/ResultSummary.tsx
- inji-verify/src/components/Home/VerificationSection/ScanQrCode.tsx
- inji-verify/src/components/Home/VerificationSection/UploadQrCode.tsx
- inji-verify/src/components/PageTemplate/Navbar.tsx
- inji-verify/src/components/commons/AlertMessage.tsx
- inji-verify/src/components/commons/PreloadImages.tsx
- inji-verify/src/components/misc/CheckingForInternetConnectivity.tsx
> [INJIVER-278] Fixed build issues during sonar analysis

- ui-test/TestNg.xml
- ui-test/browserstack.yml
- ui-test/pom.xml
- ui-test/src/test/java/utils/BaseTest.java
inji-verify browser stack integration
> MOSIP-34140 inji-verify browser stack integration

- inji-verify/src/utils/config.ts
Added user facing error code and messages as per inji web response
> [INJIVER-445] Added user friendly error messages to inji verify

- inji-verify/package-lock.json
- inji-verify/package.json
[INJIVER-609]
Bumped up version of pixel pass to 0.2.1
[INJIVER-609]: https://mosip.atlassian.net/browse/INJIVER-609?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [INJIVER-609]

- ui-test/src/main/java/base/BasePage.java
- ui-test/src/main/java/pages/HomePage.java
- ui-test/src/main/java/pages/ScanQRCodePage.java
- ui-test/src/main/java/pages/UploadQRCode.java
- ui-test/src/test/java/runnerfiles/Runner.java
- ui-test/src/test/java/stepdefinitions/StepDef.java
- ui-test/src/test/java/utils/BaseTest.java
- ui-test/src/test/resources/featurefiles/UploadQRCodepage.feature
- ui-test/src/test/resources/featurefiles/scanQRcode.feature
INJIVER-606 sync code with develop
> INJIVER-606 sync code with develop

- inji-verify/.gitignore
- inji-verify/package-lock.json
- inji-verify/package.json
- inji-verify/src/redux/features/verification/verification.saga.ts
- inji-verify/src/types/data-types.ts
- inji-verify/src/utils/qr-utils.js
https://mosip.atlassian.net/browse/INJIVER-644
> [INJIVER-644] - Latest PixelPass integration to support old Surnbird VC QR codes

- ui-test/README.md
- ui-test/pom.xml
> updated pom and readme

- ui-test/src/test/java/utils/BaseTest.java
> updated basetest

- ui-test/src/main/java/pages/HomePage.java
- ui-test/src/main/java/pages/ScanQRCodePage.java
- ui-test/src/main/java/pages/VpVerification.java
- ui-test/src/test/java/constants/UiConstants.java
- ui-test/src/test/java/stepdefinitions/StepDef.java
- ui-test/src/test/java/utils/BaseTest.java
- ui-test/src/test/resources/config.json
- ui-test/src/test/resources/featurefiles/BLE.feature
- ui-test/src/test/resources/featurefiles/UploadQRCodepage.feature
- ui-test/src/test/resources/featurefiles/homepage.feature
- ui-test/src/test/resources/featurefiles/scanQRcode.feature
- ui-test/src/test/resources/featurefiles/vpVerification.feature
This task involves revising and enhancing the existing UI automation test cases to align with the updated design and functionality of the INJI verification interface. The goal is to ensure comprehensive test coverage for the new user interface changes.
> Update UI Automation Test Cases for the New INJI Verification Interface "INJIVER-896"

- ui-test/README.md
MOSIP-39695 - Updated the README file
> MOSIP-39695 - Updated the README file

- verify-ui/src/pages/OvpRedirect.tsx
- UTF handling while decoding the QR data for Online sharing VC
https://mosip.atlassian.net/browse/INJIWEB-1471
> [INJIWEB-1471]: Online sharing VC ensure UTF8 handling while decoding QR

- verify-ui/src/redux/features/verification/verification.saga.ts
- verify-ui/src/types/mosip-pixelpass.d.ts
[INJIWEB-1430](https://mosip.atlassian.net/browse/INJIWEB-1430) - As part of adapting KMP pixelpass artifacts in mimoto.
[INJIWEB-1430]: https://mosip.atlassian.net/browse/INJIWEB-1430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [INJIWEB-1430]: [Develop]Condition to decode string data if the stringData is Base45 Data

- verify-ui/src/redux/features/verify/verifySaga.ts
- verify-ui/src/utils/commonUtils.ts
This reverts commit da46915e5dcc238b7b3e7b567d95a089e669b953.
> Revert "[INJIVER-1086] fix wallet compatable urlencoding issue (#423)"

- verify-ui/src/redux/features/verify/verifySaga.ts
- verify-ui/src/utils/commonUtils.ts
> Revert "Revert "[INJIVER-1086] fix wallet compatable urlencoding issue (#423)""

- verify-ui/package-lock.json
- verify-ui/package.json
- verify-ui/src/components/Home/Header/VerificationMethodTabs/index.tsx
This issue was caused by older version of react-icons on node version less than 16
https://github.com/react-icons/react-icons/issues/1006
The fix is to update to 5.4.0
> [INJIVER-1104] -  NPM Sonar analysis fix for rect icons

- api-test/pom.xml
DSD-7970 - Update the POM version as 0.11.1.-SNAPSHOT
> DSD-7970 - Update the POM version as 0.11.1.-SNAPSHOT

- ui-test/pom.xml
INJIVER-896 - Updated the POM version for release
> INJIVER-896 - Updated the POM version for release

- verify-ui/src/App.tsx
- verify-ui/src/components/Home/Header/VerificationMethodTabs/index.tsx
- verify-ui/src/components/Home/VerificationSection/index.tsx
- verify-ui/src/components/PageTemplate/index.tsx
- verify-ui/src/pages/Home.tsx
- verify-ui/src/pages/Scan.tsx
- verify-ui/src/pages/Verify.tsx
Fix tab highlight in mobile view
> Injiver 935 inji verify selected tab is not been highlighted in mobile view

- ui-test/src/main/java/pages/VpVerification.java
- ui-test/src/main/java/utils/BaseTest.java
- ui-test/src/test/resources/featurefiles/vpVerification.feature
MOSIP-42928- Updated the testcase for vp verification mobile view
> MOSIP-42928- Updated the testcase for vp verification mobile view

- inji-verify-sdk/package-lock.json
- inji-verify-sdk/package.json
- inji-verify-sdk/src/components/openid4vp-verification/OpenID4VPVerification.tsx
> Revert "[INJIVER-1301] fix: duplicate status call after error on vp submission"

- inji-verify-sdk/package-lock.json
- inji-verify-sdk/package.json
Bump up sdk version from 0.15.0-beta.10 to 0.15.0-beta.11
> Injiver 1311 bump up sdk version

- verify-ui/Dockerfile
> Revert "[INJIVER-1166] - update docker base image for verify-ui"
